# -*- coding: utf-8 -*-
"""Project(IFFAT&AMNA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_JpFaPR4ZVz6fvKASx8RhVuepoQhzfn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from textblob import TextBlob


from google.colab import files
files.upload()

data=pd.read_excel("Twitter+data+in+sheets.xlsx")
data

data.head()

data.tail()

data.info()

data.describe()

data.columns

data.sort_values(by=' RetweetCount',ascending=False).head(5)

data.sort_values(by=' RetweetCount',ascending=False).tail(5)

data.shape

data[' Reach'].max()

data[' Likes'].max()

data.sort_values(by=' RetweetCount')

def getPolarity(text):
    return TextBlob(text).sentiment.polarity

data["Text"]= data[' text'].str.split()
data["Text"]= data["Text"].astype(str)
data["polarity"]=data["Text"].apply(getPolarity)
data

def getSubjectivity(text):
    return TextBlob(text).sentiment.subjectivity

data["Text"]= data[' text'].str.split()
data["Text"]= data["Text"].astype(str)
data["subjectivity"]=data["Text"].apply(getSubjectivity)
data

def getPolarity(text):
    return TextBlob(text).sentiment.polarity

data["Text"]= data[' text'].to_string()
data["polarity"]=data["Text"].apply(getPolarity)
data

data.loc[23:50,['Text' Sentiment',]]

def getSubjectivity(text):
    return TextBlob(text).sentiment.subjectivity

data["Text"]= data[' text'].to_string()
data["subjectivity"]=data[' text'].apply(getSubjectivity)
data

def get_score(val):
  if val > 0:
    return 'Postive'
  elif val < 0:
    return 'Negative'
  else:
    return 'Neutral'
data['pol_score'] = data['polarity'].apply(get_score)
data.to_excel('Twitter+data+in+sheets.xlsx')
data.describe()

plt.scatter(data[' Day'],data[' Likes'])
plt.show()

import seaborn as sns
sns.barplot(x=' Day',y=' Likes',data=data)
plt.show()

sns.lineplot(x=' IsReshare',y=' Day',data=data)
plt.show

